FitnessTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path('workouts/', include('workouts.urls')),
    path('about/', include('about.urls')),
    path('metrics/', include('metrics.urls'))
]

#urlpatterns += staticfiles_urlpatterns()

about/urls.py
from django.urls import path
from .views import about_page

urlpatterns = [
    path('', about_page, name='about_page'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path("", views.login_view, name="users-login"),
    path("register/", views.register_view, name="users-register"),
    path("logout/", views.logout_view, name="users-logout"),
    path("profile/", views.profile_view, name="users-profile"),
    path("diary/", views.diary_list, name="users-diary"),
    path("diary/entry/", views.create_diary_entry, name="new-diary-entry"),
    path("diary/<int:pk>/", views.diary_detail, name="diary-detail"),
    path("diary/update/<int:pk>/", views.update_diary_entry, name="update-diary-entry"),
    path("diary/delete/<int:pk>/", views.delete_diary_entry, name="delete-diary-entry"),
    path("goals/", views.goal_view, name="users-goal"),
    path("goals/new_goal/", views.create_goal, name="new-goal"),
    path("goals/<int:pk>/", views.goal_detail, name="goal-detail"),
    path("goals/update/<int:pk>/", views.update_goal, name="update-goal"),
    path("goals/delete/<int:pk>/", views.delete_goal, name="delete-goal"),
    path("reminders/", views.reminder_view, name="users-reminder"),   
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

GOAL_STATUS = (
    ('pending', 'Pending'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed'),
    ('failed', 'Failed'),
)

# Model for user information
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(null=True, blank=True)
    weight = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    height = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    bio = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user}\'s Profile'

# Model for user's diary information
class DiaryEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=100, default="Diary Entry")
    content = models.TextField()

    class Meta:
        verbose_name_plural = "Diary entries"
    
    def __str__(self):
        return f'{self.user}s Diary ({self.date})'

# Model for user's goal information
class Goal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default="Goal")
    description = models.TextField(blank=True)
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(choices=GOAL_STATUS, max_length=50, default="in_progress")

    def __str__(self):
        return f'{self.user}s Goals'

# Model for user's reminder information
class Reminder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reminders")
    message = models.TextField(max_length=1000)
    time = models.DateTimeField(null=False, blank=False)

    def __str__(self):
        return f'{self.user}s Reminders'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import DiaryEntry, Goal, Reminder

# Form for user login
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input',
        'placeholder': 'Username (case sensitive)',
        'maxlength': '30',
        'minlength': '1',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-input',
        'placeholder': 'Password',
        'maxlength': '30',
        'minlength': '8',
    }))

# Form for user registration
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password'})

# Form for diary content
class DiaryForm(forms.ModelForm):
    class Meta:
        model = DiaryEntry
        fields = ['title', 'content']

# Form for goal content
class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ['title', 'description', 'end_date']

# Form for reminder content
class ReminderForm(forms.ModelForm):
    time = forms.DateTimeField(
        widget=forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
    )
    class Meta:
        model = Reminder
        fields = ['message', 'time']
    
    def __init__(self, *args, **kwargs):
        super(ReminderForm, self).__init__(*args, **kwargs)
        self.fields['message'].label = ''
        self.fields['time'].label = ''

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LoginForm, UserRegisterForm, DiaryForm, ReminderForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import DiaryEntry, Reminder
from django.views.decorators.cache import cache_control
from django.db.models import Q
from .forms import LoginForm, UserRegisterForm, DiaryForm, GoalForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from .models import DiaryEntry, Goal
import logging

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

# View to allow user registraton and check for valid submission and password declaration
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('users-login')
        else:
            messages.error(request, 'Invalid Submission')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

# View to allow user login and check for valid submission and password declaration
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, form.get_user())
                return redirect('users-profile')
            else:
                messages.error(request, 'Invalid username or password. Please try again.')

        else:
            messages.error(request, 'Invalid username or password. Please try again.')


    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

# View for access to user profile
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def profile_view(request):
    return render(request, 'users/profile.html', {'user': request.user})

# View for logging out of the user's account
def logout_view(request):
    logout(request)
    return redirect('/')

# View for listing all diary entries including pagination
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def diary_list(request):
    diaries = DiaryEntry.objects.filter(user=request.user).order_by('-date')
    search = request.GET.get('search', '')
    if search:
        diaries = diaries.filter(
            Q(content__icontains=search) |
            Q(title__icontains=search) |
            Q(date__icontains=search)
        )

    p = Paginator(diaries, 5)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    return render(request, 'users/diary.html', {'page_obj': page_obj, 'search': search})

# View for diary detail additions
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def diary_detail(request, pk):
    diary_entry = get_object_or_404(DiaryEntry, pk=pk)
    return render(request, 'users/diary_detail.html', {'diary_entry': diary_entry})

# View for creating a diary entry and checking if form is valid
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def create_diary_entry(request):
    logger = logging.getLogger(__name__)
    logger.debug(request.POST)
    if request.method == "POST":
        form = DiaryForm(request.POST)
        if form.is_valid():
            diary_entry = form.save(commit=False)
            diary_entry.user = request.user
            diary_entry.save()
            return redirect('users-diary')
        else:
            logger.error(f"Form Errors: {form.errors}")
            return render(request, 'users/diary_entry.html', {'form': form})
    else:
        logger.error("Invalid request type")
        form = DiaryForm()
        return render(request, 'users/diary_entry.html', {'form': form})

# View for updating existing diaries
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update_diary_entry(request, pk):
    diary_entry = get_object_or_404(DiaryEntry, pk=pk, user=request.user)
    if request.method == "POST":
        form = DiaryForm(request.POST, instance=diary_entry)
        if form.is_valid():
            form.save()
            return redirect('diary-detail', pk=diary_entry.pk)
    else:
        form = DiaryForm(instance=diary_entry)
    return render(request, 'users/update_diary_entry.html', {'form': form, 'diary_entry': diary_entry})

# View for deleting diary entries
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_diary_entry(request, pk):
    diary_entry = get_object_or_404(DiaryEntry, pk=pk, user=request.user)
    if request.method == "POST":
        diary_entry.delete()
        return redirect('users-diary')
    return render(request, 'users/delete_diary_entry.html', {'diary_entry': diary_entry})

# View for access to the user's goals
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def goal_view(request):
    goals = Goal.objects.filter(user=request.user).order_by('end_date')
    search = request.GET.get('search', '')
    if search:
        goals = goals.filter(
            Q(title__icontains=search) |
            Q(description__icontains=search) |
            Q(start_date__icontains=search) |
            Q(end_date__icontains=search) |
            Q(status__icontains=search)
        )
    p = Paginator(goals, 6)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    return render(request, 'users/goals.html', {'search': search, 'page_obj': page_obj})

# View of specific goal details
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def goal_detail(request, pk):
    goal = get_object_or_404(Goal, pk=pk)
    return render(request, 'users/goal_detail.html', {'goal': goal})

# View for creating new goal entries
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def create_goal(request):
    logger = logging.getLogger(__name__)
    logger.debug(request.POST)
    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            new_goal = form.save(commit=False)
            new_goal.user = request.user
            new_goal.save()
            return redirect('users-goal')
        else:
            logger.error(f"Form Errors: {form.errors}")
            return render(request, 'users/new_goal.html', {'form': form})
    else:
        logger.error("Invalid request type")
        form = GoalForm()
        return render(request, 'users/new_goal.html', {'form': form})

# View for update exising goals
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update_goal(request, pk):
    goal = get_object_or_404(Goal, pk=pk, user=request.user)
    if request.method == "POST":
        form = GoalForm(request.POST, instance=goal)
        if form.is_valid():
            form.save()
            return redirect('goal-detail', pk=goal.pk)
    else:
        form = GoalForm(instance=goal)
    return render(request, 'users/update_goal.html', {'form': form, 'goal': goal})

# View for deleting goals
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_goal(request, pk):
    goal = get_object_or_404(Goal, pk=pk, user=request.user)
    if request.method == "POST":
        goal.delete()
        return redirect('users-goal')
    return render(request, 'users/delete_goal.html', {'goal': goal})

# View for accessing the email reminder functionality
@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def reminder_view(request):
    if request.method == "POST":
        form = ReminderForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

            return redirect('users-reminder')
        else:
            return redirect('users-reminder')
    else:
        reminders = Reminder.objects.filter(user=request.user)
        form = ReminderForm()
        return render(request, 'users/reminder.html', {'user': request.user, 'reminders': reminders, 'form': form})

users/templates/users/delete_diary_entry.html
{% extends "users/layout.html" %}

{% block main %}
    <h2>Delete Diary Entry</h2>
    <p>Are you sure you want to delete this entry?</p>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, Delete">
    </form>

    <a href="{% url 'diary-detail' diary_entry.pk %}">No, Go Back</a>
{% endblock %}

users/templates/users/delete_goal.html
{% extends "users/layout.html" %}

{% block main %}
    <h2>Delete Goal</h2>
    <p>Are you sure you want to delete this goal?</p>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, Delete">
    </form>

    <a href="{% url 'goal-detail' goal.pk %}">No, Go Back</a>
{% endblock %}

users/templates/users/layout.html
<!--Default Page for our Fitness Tracker-->
{% load static %}<!--loads static for stylesheet usagle in django-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Fitness Tracker{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!--<link rel="stylesheet" href="{% static 'users/style.css' %}">declares it is looking for a static item which is our css file-->
  </head>
  <body>
    {% block header %} {% endblock %}
  </body>
  <main>{% block main %} {% endblock %}</main>
  <footer style="margin-top: 40px; margin-bottom: 0px;">
    <p>&copy; 2023 Fitness Tracker. All Rights Reserved.</p>
  </footer>

  <style>
    .navbar-toggler-icon {
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'%3E%3Cpath stroke='rgba(255, 193, 7, 1)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
    }

    .nav-logo {
      width: 120px;
      height: auto;
    }

    @media (max-width: 768px) {
      .nav-logo {
        width: 80px;
      }
    }
  </style>
</html>

users/templates/users/update_diary_entry.html
{% extends "users/layout.html" %}
{% load static %}
<!-- Header for the navigation bar -->
{% block header %}
<header style="background-color: black; padding-bottom: 0;">
    <nav class="navbar navbar-expand-md justify-content-center" style="padding-top: 0; margin-top: 1.5%;">
      <a class="navbar-brand" href="{% url 'users-profile' %}" style="padding: 0;">
        <img class="nav-logo" src="{% static 'images/mac_header.jpg' %}" alt="Mac's Strength and Power Logo"/>
      </a>
      <div class="col-md-auto">
        <div class="row">
          <h1 style="color: yellow;"style="right: 40;">Mac's Strength and Power: Fitness Tracker</h1>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="row">
          <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar" style="left: 25%">
            <ul class="navbar-nav">
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'users-profile' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">Home</a>
              </li>
              <li class="nav-item mr-2 mb-2">
                <div class="dropdown-center mr-2 mb-2">
                  <button class="btn dropdown-toggle mr-2 mb-2" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black; background-color: yellow;" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">
                      Menu
                  </button>
                  <ul class="dropdown-menu" style="background-color: yellow; overflow: hidden; padding-right: 15px; text-align: center; border: 1px solid gray;">
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'create_workout' %}" style="color: black; background-color: yellow !important; padding: 0;" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Create A Workout</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'workout_list' %}" style="color: black; background-color: yellow !important; padding: 0;" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Workout List</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'users-diary' %}" aria-disabled="true" style="color: black; background-color: yellow !important; padding: 0" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Diary</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'users-goal' %}" style="color: black; background-color: yellow !important; padding: 0" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Goals</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'metrics' %}" style="color: black; background-color: yellow !important; padding: 0;" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Weigh-In</a></li>
                  </ul>
                </div>
              </li>
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'users-reminder' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">Create Email Reminders</a>
              </li>
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'about_page' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">About</a>
              </li>
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'users-logout' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
</header>  
{% endblock %}

{% block main %}

    <body style="background-color: black;">

        <!-- Messages -->
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}

        <!-- Update Diary Entry Heading -->
        <h1 style="color: yellow; text-align: center;">Update Diary Entry: {{ diary_entry.pk }}</h1>

        <!-- Update Diary Entry Form -->
        <form method="post" action="{% url 'update-diary-entry' diary_entry.pk %}" class="form">
            {% csrf_token %}
            <div class="form-group mb-4">
                <label for="id_title" class="form-label" style="color: yellow;">Title</label>
                <input type="text" id="id_title" name="title" class="form-control bg-dark text-white" value="{{ form.title.value|default_if_none:diary_entry.title }}" required>
            </div>
            <div class="form-group mb-4">
                <label for="id_content" class="form-label" style="color: yellow;">Content</label>
                <textarea rows="40" cols="20" id="id_content" name="content" class="form-control bg-dark text-white" rows="5" required>{{ form.content.value|default_if_none:diary_entry.content }}</textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-warning text-black">Update Entry</button>
            </div>
        </form>
    </body>

{% endblock %}

users/templates/users/update_goal.html
{% extends "users/layout.html" %}
{% load static %}
<!-- Header for the navigation bar -->
{% block header %}
<header style="background-color: black; padding-bottom: 0;">
    <nav class="navbar navbar-expand-md justify-content-center" style="padding-top: 0; margin-top: 1.5%;">
      <a class="navbar-brand" href="{% url 'users-profile' %}" style="padding: 0;">
        <img class="nav-logo" src="{% static 'images/mac_header.jpg' %}" alt="Mac's Strength and Power Logo"/>
      </a>
      <div class="col-md-auto">
        <div class="row">
          <h1 style="color: yellow;"style="right: 40;">Mac's Strength and Power: Fitness Tracker</h1>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="row">
          <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar" style="left: 25%">
            <ul class="navbar-nav">
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'users-profile' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">Home</a>
              </li>
              <li class="nav-item mr-2 mb-2">
                <div class="dropdown-center mr-2 mb-2">
                  <button class="btn dropdown-toggle mr-2 mb-2" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black; background-color: yellow;" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">
                      Menu
                  </button>
                  <ul class="dropdown-menu" style="background-color: yellow; overflow: hidden; padding-right: 15px; text-align: center; border: 1px solid gray;">
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'create_workout' %}" style="color: black; background-color: yellow !important; padding: 0;" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Create A Workout</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'workout_list' %}" style="color: black; background-color: yellow !important; padding: 0;" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Workout List</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'users-diary' %}" aria-disabled="true" style="color: black; background-color: yellow !important; padding: 0" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Diary</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'users-goal' %}" style="color: black; background-color: yellow !important; padding: 0" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Goals</a></li>
                      <li class="d-grid"><a class="dropdown-item" href="{% url 'metrics' %}" style="color: black; background-color: yellow !important; padding: 0;" onmouseover="this.style.backgroundColor='black', this.style.color='yellow'" onmouseout="this.style.backgroundColor='yellow', this.style.color='black'">Weigh-In</a></li>
                  </ul>
                </div>
              </li>
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'users-reminder' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">Create Email Reminders</a>
              </li>
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'about_page' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">About</a>
              </li>
              <li class="nav-item mr-2 mb-2">
                <a class="btn" href="{% url 'users-logout' %}" style="color: black; background-color: yellow;" class="btn" onmouseover="this.style.borderColor='yellow'" onmouseout="this.style.borderColor='black'">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
</header>
{% endblock %}

{% block main %}

    <body style="background-color: black;">

        <!-- Messages -->
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}

        <!-- Update Diary Entry Heading -->
        <h1 style="color: yellow; text-align: center;">Update Goal: {{ goal.pk }}</h1>

        <!-- Update Diary Entry Form -->
        <form method="post" action="{% url 'update-goal' goal.pk %}" class="form">
            {% csrf_token %}
            <div class="form-group mb-4">
                <label for="id_title" class="form-label" style="color: yellow;">Title</label>
                <input type="text" id="id_title" name="title" class="form-control bg-dark text-white" value="{{ form.title.value|default_if_none:goal.title }}" required>
            </div>
            <div class="form-group mb-4">
                <label for="id_description" class="form-label" style="color: yellow;">Content</label>
                <textarea rows="20" cols="20" id="id_description" name="description" class="form-control bg-dark text-white" required>{{ form.description.value|default_if_none:goal.description }}</textarea>
            </div>
            <div class="form-group mb-4">
                <label for="id_end_date" class="form-label" style="color: yellow;">End Date: {{ goal.end_date|date:"Y-m-d" }}</label>
                <input type="date" id="id_end_date" name="end_date" class="form-control bg-dark text-white" required>{{ form.end_date.value }}</input>
            </div>
            <div class="form-group">
                <button type="submit" class="btn col-12 mb-4" style="color: black; background-color: yellow;">Update Goal</button>
            </div>
        </form>
    </body>
{% endblock %}